### ISSUE TITLE
Redis 세션 서버 설정 및 연결

### ISSUE THREAD

**Issue by rang21c** [boostcampwm-2022/web16-Codocs#11]
### 설명
---
깃허브 OAuth 로그인에 세션을 이용한 인가 작업을 구현하기 위해 Redis 세션 서버를 적용한다.

### 완료 조건
---
- [ ] Redis 세션 서버 생성 및 적용
- [ ] 작동테스트

**Comment by komplamoose** [comment]
기획 변경으로 이슈 Closed
