### ISSUE TITLE
[Bug] 배포판에서 마크다운 프리뷰 기능 동작 안함

### ISSUE THREAD

**Issue by komplamoose** [boostcampwm-2022/web16-Codocs#129]
### 설명
---

#48 

이 이슈랑 같은 문제로 보입니다. 

### 완료 조건
---
- [x] easymde 버전 다운그레이드

**Comment by iyu88** [comment]
서버에 설치된 버전이 2.18 버전이었어요. 다운그레이드 했어요~

<img width="1392" alt="스크린샷 2023-02-24 20 04 59" src="https://user-images.githubusercontent.com/31645195/221164377-1d03c7a4-b960-4787-86f4-c56be1635177.png">
