### ISSUE TITLE
styled-components 글로벌 스타일 정의

### ISSUE THREAD

**Issue by iyu88** [boostcampwm-2022/web16-Codocs#3]
### 설명
`styled-components` 를 설치하고 전체 웹 애플리케이션에서 사용할 글로벌 스타일을 정의합니다.

### 완료 조건
---
- [x] styled-components 설치 
- [x] styled-reset 설치 
- [x] 글로벌 스타일 정의

**Comment by komplamoose** [comment]
### Memo

디자인 확정 후 Font, Color, Variable 스타일 정의 예정
